# Generated by Django 4.1.1 on 2022-09-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
