# Generated by Django 4.1.1 on 2022-09-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_end_date_event_start_date_alter_event_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="end_date",
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
