# Generated by Django 4.1.1 on 2022-09-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_remove_event_end_date_alter_comment_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
    ]
