# Generated by Django 4.1.1 on 2022-09-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="end_date",
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="event",
            name="seats",
            field=models.IntegerField(default=0),
        ),
    ]
