# Generated by Django 4.1.1 on 2022-09-21 11:04

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="video",
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
