# Generated by Django 4.1.1 on 2022-09-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="video",
            new_name="video_url",
        ),
    ]
